name: Bug Report
description: File a bug report to help us improve Obvivlorum
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Run command '....'
        4. See error
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Core Orchestrator
        - Security Manager
        - Human-in-the-Loop
        - Smart Provider Selector
        - Structured Logger
        - AION Protocol
        - Unified Launcher
        - Docker Sandbox
        - Web Interface
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., Windows 11, Ubuntu 22.04, macOS 13
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: e.g., Python 3.11.5
    validations:
      required: true

  - type: input
    id: obvivlorum-version
    attributes:
      label: Obvivlorum Version
      description: What version of Obvivlorum are you using?
      placeholder: e.g., v2.0.0 or commit hash
    validations:
      required: true

  - type: dropdown
    id: launch-mode
    attributes:
      label: Launch Mode
      description: Which launch mode were you using?
      options:
        - core (default)
        - legacy
        - gui
        - background
        - sandbox
        - test
        - web
        - parrot
        - security
        - minimal
    validations:
      required: false

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Please share any relevant configuration (config_optimized.json sections, environment variables, etc.)
      render: json
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Before submitting, please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided sufficient information to reproduce the issue
          required: true
        - label: I have removed any sensitive information from logs/configuration
          required: true