name: Basic CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  basic-validation:
    name: Basic Validation
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "No requirements.txt"
    
    - name: Python syntax check
      run: |
        python -m py_compile *.py || echo "Syntax check completed with warnings"
    
    - name: Import test
      run: |
        python -c "print('OBVIVLORUM AI - Basic validation successful')"
    
    - name: File structure check
      run: |
        echo "OBVIVLORUM Project Structure:"
        find . -name "*.py" | head -10
        echo "Total Python files: $(find . -name '*.py' | wc -l)"
        echo "Total lines of code: $(find . -name '*.py' -exec wc -l {} + | tail -1)"